### ISSUE TITLE
一些 test 不通过

### ISSUE THREAD

**Issue by eternalsky** [uxcore/uxcore-mention#11]
@macisi 师兄，今天看了一下 mention，感觉里面有些 test 跑不过去，里面会从实例中取 editor，但是实际上 Mention 里并没有给 editor 赋值，这块能否看下应该如何改~

**Comment by macisi** [comment]
直接给 Mention 里的 editor 加 ref 试试？

**Comment by eternalsky** [comment]
@macisi 这一块是因为后面几次修改里把这个 editor 干掉了吗~

**Comment by eternalsky** [comment]
https://github.com/uxcore/uxcore-mention/blob/master/tests/Mention.spec.js#L85

**Comment by gbk** [comment]
tc 已经重写过了。
