### ISSUE TITLE
在contenteditable容器中使用时，怎么限制内容长度

### ISSUE THREAD

**Issue by WisestCoder** [uxcore/uxcore-mention#15]
用法如下：
![image](https://user-images.githubusercontent.com/21785332/40227225-77882bb6-5ac0-11e8-805d-2a45557c4e1f.png)

想知道怎么才能限制内容的长度

**Comment by gbk** [comment]
不知道这样能否解决你的问题，onChange 检测内容的变更是准确的，可以在此做一些处理。
```jsx
        <Mention
          matchRange={[2, 6]}
          source={source}
          onChange={(e, content) => {
            if (content.length > 100) {
              this.setState({content: content.substring(0, 100)});
              console.log('overflow!!');
            }
          }}
          formatter={formatter}
        >
          <ContenteditableEditor
            width="100%"
            height="auto"
            placeholder="contenteditable editor placeholder"
            defaultValue={'defaultValue'}
            value={this.state.content}
          />
        </Mention>
```

**Comment by WisestCoder** [comment]
@gbk 感谢您的回复。
但目前我们的组件是非数控组件（因为受控组件的话，每次输入，编辑框的焦点都会重置在文本最前面）
非受控组件，我们只能操作dom来改变文本值，我的做法是在onChange中做一下代码：
```javascript
onChange={(e, content) => {
  const mention = ReactDOM.findDOMNode(this.refs.editor);
  const editor = mention.getElementsByClassName('kuma-mention-editor')[0];
  editor.innerHTML = content.substring(0, 100);
}}
```
这样做之后，会造成无限死循环，原因是：onChange时改变了文本值，dom结构发生变化，会触发MutationObserver，Observer里面又执行了onChange，所以无限循环了。

**Comment by WisestCoder** [comment]
如果按照你上面的代码改成受控组件，会有bug。
比如我已经输入了最大长度100个字符，我在编辑框中的末尾再输入一个字符时，此时会进this.props.onChange，在onChange中，会调用`this.setState({content: content.substring(0, 100)});`，会触发组件的重新render，同时会进入contenteditable的componentWillReceiveProps生命周期，但是由于nextProps.value 和 this.props.value的值都是content.substring(0, 100)后的值，此时是相等的，所以导致判断中的`this.editor.innerHTML = nextProps.value`代码不执行，所以可以无限输入，不能做到控制最大长度

**Comment by WisestCoder** [comment]
@gbk  可以加个maxLength属性，先支持一下我的需求吗😢😢

**Comment by gbk** [comment]
@WisestCoder 你可以提个 PR 么？

**Comment by gbk** [comment]
非常感谢！
你的变更已经发布到 v0.4.0 版本中
