### ISSUE TITLE
TypeError: Cannot read property 'getSelection' of undefined

### ISSUE THREAD

**Issue by ikorgik** [uxcore/uxcore-mention#21]
Hi, I have `TypeError: Cannot read property 'getSelection' of undefined` error when I try to integrate ContenteditableEditor from the first example: http://uxco.re/components/mention/#code-box-components-mention-demo-contenteditable

It happens because the library requires <script src="//alinw.alicdn.com/uxcore/uxcore-lib/??rangy/1.3.0/rangy-core.min.js" /> included on the page.

Do you need to enhance the code / update documentation for it?

**Comment by gbk** [comment]
@ikorgik thank you for your suggestion! and the document was updated.
